jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
               path: target/surefire-reports
      - run:
          name: Upload to CodeCov
          command: bash <(curl -s https://codecov.io/bash)