version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/my-reports
      - run:
          name: Upload to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
      - codecov/upload:
          file: target/my-reports